name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  device_info_plus: ^4.1.2
  flutter:
    sdk: flutter
  flutter_background_service: ^2.1.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_blue:
    path: ../

flutter:
  uses-material-design: true
